# Generated by Django 5.0 on 2024-02-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='dest/hotels')),
            ],
        ),
    ]
