# Generated by Django 5.0 on 2024-01-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('loc', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour/trips')),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dest.location')),
            ],
        ),
    ]
