# Generated by Django 5.0 on 2024-01-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=200)),
                ('total_rooms', models.IntegerField()),
                ('d_rooms', models.IntegerField()),
                ('p_rooms', models.IntegerField()),
                ('d_rent', models.IntegerField()),
                ('p_rent', models.IntegerField()),
                ('dimage', models.ImageField(blank=True, null=True, upload_to='rooms/deluxe')),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='rooms/premium')),
                ('room_status', models.CharField(default='notbooked', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accom.accommodation')),
            ],
        ),
    ]
