# Generated by Django 5.0 on 2024-01-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom', '0002_roomdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='room/premium'),
        ),
    ]
