# Generated by Django 5.0 on 2024-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom', '0004_bookroom_remove_roomdetails_room_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookroom',
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
