# Generated by Django 5.0 on 2024-01-15 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom', '0005_delete_bookroom_roomdetails_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(default='notbooked', max_length=20)),
                ('user_name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('cin_date', models.DateField()),
                ('cout_date', models.DateField()),
                ('comfort', models.CharField(max_length=30)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('noof_rooms', models.IntegerField()),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accom.roomdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
