# Generated by Django 5.0 on 2024-02-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accom', '0008_remove_bookroom_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='rtype',
        ),
    ]
